#!/bin/bash

echo -e "Cpp:      \c"
find ~/Desktop ! -path "/home/tony/Desktop/aoapc-bac2nd/*" -name "*.cpp" | xargs cat | wc -l

echo -e "Markdown: \c"
find ~/Desktop ! -path "/home/tony/Desktop/aoapc-bac2nd/*" -name "*.md" | xargs cat | wc -l

echo -e "Python:   \c"
sudo find ~ -path "*/manim/manim/manim_projects/*.py" -o -path "*/Desktop/*.py" | xargs cat | wc -l

find ~/Desktop ! -path "/home/tony/Desktop/aoapc-bac2nd/*" -name "*.cpp" | xargs cat | wc -l > ~/cnt_cpp

find ~/Desktop ! -path "/home/tony/Desktop/aoapc-bac2nd/*" -name "*.md" | xargs cat | wc -l > ~/cnt_md

sudo find ~ -path "*/manim/manim/manim_projects/*.py" -o -path "*/Desktop/*.py" | xargs cat | wc -l > ~/cnt_py

cd ~
./cnt_add

echo -e "\nAll:      \c"
cat cnt_ans

rm cnt_py
rm cnt_cpp
rm cnt_md
rm cnt_ans
