#!/bin/bash

hel="--help"
if [ -n "$1" ]; then
	if [[ $1 != $hel ]]; then
		echo "Reading file : $1.cpp"
		if [ ! -f "$1.cpp" ] ; then
			echo "Can't read file : $1.cpp"
			exit
		fi

		echo "Reading file : $1.in"
		if [ ! -f "$1.in" ] ; then
			echo "Can't read file : $1.in"
			exit
		fi

		echo "Reading file : $1.out"
		if [ ! -f "$1.out" ] ; then
			echo "Can't read file : $1.out"
			exit
		fi

		echo -e "Files are ready for compile."

		g++ -o $1 $1.cpp -g -lm
		if [ $? -ne 0 ] ; then
			echo -e "\n\nCompile Error！"
			exit
		fi
		echo -e "\nCompiled successfully\n"

		./$1 < $1.in > a.out
		diff $1.out a.out -w
		if [ $? -ne 0 ] ; then
			echo -e "\n\nWrong Answer！"
			exit
		fi

		cat a.out
		echo -e "\nAccepted!"
		# /usr/bin/time -f "time: %U\n" ./$1 < $1.in > a.out

		y="y"
		# read -p "是否使用gedit打开文件?(y/n) > " op1
		# if [ $op1 = $y ] ; then
		# 	gedit $1.cpp
		# fi

		read -p "Archive files?(y/n) > " op
		if [ $op = $y ] ; then
			read -p "Archive folder > " fold
			rm $1
			rm a.out
			mv $1.out $fold/outputs/
			mv $1.cpp $fold/codes/
			mv $1.in $fold/inputs/
			echo "Archive successfully"
			sleep 2s
			clear
		fi
	else
		echo -e "帮助:\n\t使用 run <filename> 来运行filename.cpp 并检查"
		echo -e "\t使用 run --help 来查看帮助"
	fi	
else
	echo -e "\033[1;31m[ERROR]\033[0m 无传入参数"
	echo -e "\trun --help 查看帮助"
	false
fi
